### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by jxxtin** [ianhuang0630/BlenderAlchemyOfficial#3]
Hello @ianhuang0630,

Thank you for your impactful research. 

After updating from the deprecated gpt model([link](https://github.com/ianhuang0630/BlenderAlchemyOfficial/blob/6900dbb8bfc7947b5feb338c9847b700b1500e1b/agents.py#L38)) to gpt-4o-mini, 

I encountered an following error. 
```
2024-11-11 23:20:08.198 | WARNING  | refinement_process:thread:74 - thread 0 LLM querying failed with error:
'text'
'text'
2024-11-11 23:20:08.360 | WARNING  | refinement_process:thread:74 - thread 1 LLM querying failed with error:
'text'
'text'
...


Traceback (most recent call last):
  File "/Users/miniconda3/envs/blenderalch/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/miniconda3/envs/blenderalch/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Desktop/BlenderAlchemyOfficial/refinement_process.py", line 96, in thread
    results[idx] = (code_path, render_path, p_ans.raw)  # The in-place modification of results with the 3-tuple
UnboundLocalError: local variable 'p_ans' referenced before assignment
...


Traceback (most recent call last):
  File "/Users/Desktop/BlenderAlchemyOfficial/main.py", line 77, in <module>
    refinement(config,
  File "/Users/Desktop/BlenderAlchemyOfficial/refinement_process.py", line 435, in refinement
    results = tree_branch(breadth, tuner_question,
  File "/Users/Desktop/BlenderAlchemyOfficial/refinement_process.py", line 114, in tree_branch
    assert all([el is not None for el in results])
AssertionError
```

Could I get some help with this?

Thanks!

**Comment by ianhuang0630** [comment]
Hi! Thanks for your interest in our work.

Please `git pull` from the TaskSolver github again (https://github.com/ianhuang0630/TaskSolver) -- it's been updated now such that the problem you encountered should go away.

Please let me know if you run into additional issues!

**Comment by ianhuang0630** [comment]
Additionally, the  default model has been changed to `gpt-4-turbo` : https://github.com/ianhuang0630/BlenderAlchemyOfficial/blob/main/agents.py#L38

**Comment by jxxtin** [comment]
Thank @ianhuang0630  for addressing the issue.

I'm considering using llama which is based on VLM from ollma due to the cost concerns with GPT4V. 

Is it possible to perform the same tasks with it? (e.g., Blend Shapes)

I'm asking because the current examples in the readme seem to utilize only a language model like mistral.
