### ISSUE TITLE
Issues due to changes in LLM model

### ISSUE THREAD

**Issue by jxxtin** [ianhuang0630/BlenderAlchemyOfficial#4]
Hello, @ianhuang0630 

when i excute the following command with fixed configs/blendshapes_ew.yaml (I changed GPT4V to mistral)
```
python main.py --starter_blend starter_blends/face_animation.blend --blender_base blender_base/bodyshape_shapekeys.py  --blender_script blender_scripts/shapekeys_examples/facialshapekeys.py --config configs/blendshapes_ew.yaml
```

I encountered an following error 
```
Exception in thread Thread-2 (thread):
Traceback (most recent call last):
  File "/root/anaconda3/envs/blenderalch/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/blenderalch/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/projects/BlenderAlchemyOfficial/refinement_process.py", line 96, in thread
    results[idx] = (code_path, render_path, p_ans.raw)  # The in-place modification of results with the 3-tuple
UnboundLocalError: local variable 'p_ans' referenced before assignment
__delitem__

2024-11-27 17:29:26.356 | WARNING  | refinement_process:thread:74 - thread 2 LLM querying failed with error:
__delitem__
Exception in thread Thread-3 (thread):
Traceback (most recent call last):
  File "/root/anaconda3/envs/blenderalch/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/blenderalch/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/projects/BlenderAlchemyOfficial/refinement_process.py", line 96, in thread
    results[idx] = (code_path, render_path, p_ans.raw)  # The in-place modification of results with the 3-tuple
UnboundLocalError: local variable 'p_ans' referenced before assignment
__delitem__
```

Thank you for your help!

**Comment by ianhuang0630** [comment]
Hi,

Did you run  `ollama pull mistral` in the terminal before attempting to use the model? (https://github.com/ianhuang0630/TaskSolver/tree/main?tab=readme-ov-file#optional-ollama)

What does your yaml file look like?

Best,
Ian

**Comment by jxxtin** [comment]
Hello, @ianhuang0630 

I've been working with the blendshapes_ew.yaml using a default config file and have successfully created code using mistral as the edit_generator_type. 

Now, I want to try out edit_generator_type and state_evaluator_type with VLM.

I've encountered a problem when using Llama 3.2V. 

It looks like I need to make some changes to the [prepare_payload](https://github.com/ianhuang0630/TaskSolver/blob/6c7b5b0db1935ea0ac1b43c3bb944585b167f71c/tasksolver/ollama.py#L61) function to support these features. 

Could you guide me on how to adjust this function to work with the updates in Llama 3.2V for edit_generator_type and state_evaluator_type?
